nome=input ('Qual e o seu nome?')
idade= int(input('qual e a sua idade?' ))
programacao=input ('Qual e a sua linguagem de programacao favorita?')
ano_atual= int(input('em que ano estamos?' ))
ano_nascimento= (ano_atual-idade)
print (f"meu nome: {nome}\nminha idade: {idade}\nLinguagem de programacao: {programacao}\nano atual: {ano_atual}\nano nascimento {ano_nascimento}")
